from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4

def generate_pdf(filename, eda_text, dashboards, sql_queries):
    styles = getSampleStyleSheet()
    story = []

    story.append(Paragraph("<b>AI Analytics Report</b>", styles["Title"]))
    story.append(Spacer(1, 20))
    story.append(Paragraph("Generated by Offline AI Analytics Engineer", styles["Normal"]))
    story.append(PageBreak())

    story.append(Paragraph("<b>Executive EDA Summary</b>", styles["Heading1"]))
    story.append(Paragraph(eda_text.replace("\n", "<br/>"), styles["Normal"]))
    story.append(PageBreak())

    for section, charts in dashboards.items():
        if charts:
            story.append(Paragraph(f"<b>{section} Dashboard</b>", styles["Heading1"]))
            story.append(Spacer(1, 12))

            for c in charts:
                story.append(Paragraph(c["title"], styles["Heading3"]))
                story.append(Image(c["image"], width=400, height=250))
                story.append(Spacer(1, 12))

            story.append(PageBreak())

    story.append(Paragraph("<b>SQL Appendix</b>", styles["Heading1"]))
    for q in sql_queries:
        story.append(Paragraph(f"<pre>{q}</pre>", styles["Code"]))
        story.append(Spacer(1, 8))

    pdf = SimpleDocTemplate(filename, pagesize=A4)
    pdf.build(story)
